name: 'Simple GCP Deployment'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  TF_VERSION: "1.5.0"

jobs:
  simple-deploy:
    name: 'Simple Terraform Deploy'
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v1

    - name: 'Create terraform.tfvars'
      run: |
        cat > terraform.tfvars << EOF
        project_id = "${{ secrets.GCP_PROJECT_ID }}"
        region = "us-central1"
        bucket_name = "${{ secrets.GCP_PROJECT_ID }}-simple-bucket-${{ github.run_number }}"
        environment = "production"
        instance_name = "simple-vm"
        machine_type = "e2-micro"
        zone = "us-central1-a"
        boot_disk_image = "projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts"
        boot_disk_size = 10
        EOF

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'Terraform Plan'
      run: terraform plan

    - name: 'Terraform Apply (main branch only)'
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "🚀 Deploying simple cost-optimized infrastructure..."
        terraform apply -auto-approve
        
        echo "✅ Deployment completed!"
        echo "💰 Estimated monthly cost: ~$3.92"
        
        # Show what was created
        echo "📋 Resources created:"
        terraform output -json | jq -r 'to_entries[] | "- \(.key): \(.value.value)"'

    - name: 'Show Plan (PR only)'
      if: github.event_name == 'pull_request'
      run: |
        echo "📋 This would create:"
        echo "- Preemptible e2-micro VM (~$3.50/month)"
        echo "- 10GB standard disk (~$0.40/month)"
        echo "- Cloud Storage bucket (~$0.02/month)"
        echo "- Total: ~$3.92/month"